apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sp-hello
  labels:
    app:  sp-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sp-hello
  template:
    metadata:
      labels:
        app: sp-hello
    spec:
      containers:
      - name: sp-hello-pod
        image: ghcr.io/ignaciylipm/sp-hello:1.0  # {"$imagepolicy": "tanzu-continuousdelivery-resources:sp-hello-world"}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sp-hello-service
spec:
  selector:
    app: sp-hello
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
